module.exports = {
    GET_LIST_PRODUCT : 'GET_LIST_PRODUCT',
    GET_PRODUCT_DETAIL : 'GET_PRODUCT_DETAIL',

    GET_LOGIN_INFO: 'GET_LOGIN_INFO',
    LOGIN_INFO: 'LOGIN_INFO',
    LOGOUT: 'LOGOUT'

}